routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/syarat-dan-ketentuan', function() {
    return view('frontend.help.syarat-dan-ketentuan');
});

/*
|--------------------------------------------------------------------------
| Buddy Routes
|--------------------------------------------------------------------------
*/
Route::prefix('buddy')->name('buddy.')->group(function() {
    Route::get('/','BuddyController@index')->name('home');
    
    // Route for booking a buddy
    Route::get('/{id}/book', 'BuddyController@book')->name('book');
    Route::post('/{id}/book', 'BuddyController@book')->name('book');
    Route::get('/book/success', function() {
        return view('frontend/buddy/order-success');
    })->name('book.success');
    
    // Buddy's profile
    Route::get('/{id}', 'BuddyController@profile')
        ->where(['id' => '[0-9]+'])
        ->name('profile');

    Route::post('/create', 'BuddyController@create')->name('create');
    
    Route::get('/search','BuddyController@search')->name('search');

    Route::post('order/accept','BuddyController@acceptOrder')->name('order.accept');
    Route::post('order/decline','BuddyController@declineOrder')->name('order.decline');
});

Route::get('/become-a-buddy', 'BuddyController@join')->name('buddy.join');

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::prefix('admin')
    ->name('admin.')
    ->namespace('Admin')
    ->group(function() {
    
    route::get('buddy', 'BuddyController@index')->name('buddy');
    route::get('verification', 'BuddyController@verification')->name('verification');
    //  route::get('buddy/verification', function () {
    //     return 'hello';
    // });
    // route::get('buddy/verification', 'BuddyController@verification')->name('verification')
      

    route::delete('buddy/{id}', 'BuddyController@delete')->name('buddy.delete');

    route::get('buddy/view/{id}', 'BuddyController@view')->name('buddy.view');
    
    Route::get('order', 'OrderController@index')->name('order');
    Route::put('order/status', 'OrderController@orderStatus')->name('order.status');

    Route::get('order/{id}', 'OrderController@view')->name('order.item');
    Route::post('order/confirm', 'OrderController@confirm')->name('order.confirm');
    
    Route::get('order/{id}/update', 'OrderController@updateView')->name('order.update.view');
    Route::put('order/{id}/update', 'OrderController@update')->name('order.update');
    
    Route::get('/', 'HomeController@index')->name('home');
});

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/
Route::prefix('user')
    ->name('user.')
    ->group(function() {
    
    Route::put('/password', 'UserController@changePassword')->name('changePassword');
    Route::post('/update', 'UserController@update')->name('update');
    Route::post('/update/picture', 'UserController@updatePicture')->name('updatePicture');
});


Route::prefix('bantuan')->name('help.')->group(function () {
    Route::get('/', function() {
        return view('frontend.help.menggunakan-jasa-kami');
    })->name('home');
    Route::get('menggunakan-jasa-kami', function() {
        return view('frontend.help.menggunakan-jasa-kami');
    })->name('menggunakan-jasa-kami');
    Route::get('faq', function() {
        return view('frontend.help.faq');
    })->name('faq');
});

/*
|--------------------------------------------------------------------------
| About Us
|--------------------------------------------------------------------------
*/
Route::get('/about-us', function() {
    return view('frontend.about-us');
});

/*
|--------------------------------------------------------------------------
| Dashboard
|--------------------------------------------------------------------------
*/
Route::prefix('dashboard')->name('dashboard.')->group(function() {
    Route::get('/','DashboardController@index')->name('home');
    Route::get('buddy', 'DashboardController@buddy')->name('buddy');
    Route::get('order', 'DashboardController@order')->name('order');
    Route::get('settings', 'DashboardController@settings')->name('settings');
});

/*
|--------------------------------------------------------------------------
| Email verification
|--------------------------------------------------------------------------
*/
Route::get('/register/verification', function() {
    return view('email-verif.verification');
});
Route::get('/verification', function() {
    return view('email-verif.must-verif');
});

Route::get('/register/verification/resend', 'RegisterController@resend');
Route::post('/register/verification/resend', 'RegisterController@resend');
Route::get('/verifyemail/{token}', 'RegisterController@verify');


/*
|--------------------------------------------------------------------------
| API
|--------------------------------------------------------------------------
*/
Route::get('/api/country', 'CountryController@index');
Route::get('/api/city', 'CountryController@city');
Route::get('/api/price', 'CountryController@price');

/*
|--------------------------------------------------------------------------
| For testing purposes
|--------------------------------------------------------------------------
*/
// Route::post('testpost', function(\Illuminate\Http\Request $request) {
//     echo '<pre>';
//     var_dump($request->all());
//     echo '</pre>';
// });

// Route::get('testviewmail', function() {
//     $user = \App\Models\User::find(1);

//     return view ('mail.email-verification', compact('user'));
// });

// Route::get('testmail', function() {
//     $order = \App\Order::first();
//     Mail::to('husnimun@gmail.com')
//     ->send(new \App\Mail\ResetPassword('asdwasdwasdw'));
// });

// Route::get('testmail', function() {
//     $user = \App\Models\User::find(3);
//     Mail::to('husnimunaya@gmail.com')
//         ->send(new \App\Mail\EmailVerification($user));
// });

// Route::get('mailable', function() {
//     $order = \App\Order::find(1);

//     return new App\Mail\OrderReceivedBuddy($order);
// });

// Route::get('test', function() {
//     return view('test');
// });

// Route::get('buddysearch', function(\Illuminate\Http\Request $request) {
//     $location = $request->input('location');        
//     $buddies = \App\Buddy::search($location)->get();

//     return response()->json(['data' => $buddies], 200, [], JSON_NUMERIC_CHECK);
// });

resources/views/frontend/about-us.blade.php
@extends('frontend.layouts.main')

@section('content')
    <div class="my-hero">
        <div class="container">
            <div class="row">
                <div class="col-md-6 order-2 order-md-1">
                    <div class="my-hero__body">
                        <h1 class="my-hero__title">Tentang Kami</h1>
                        <p>
                           Travel Buddy adalah sebuah platform yang mempertemukan Anda dengan orang Indonesia di negara tujuan yang akan menemani selama perjalanan. Kami menawarkan fleksibilitas dalam mengatur dan merencanakan perjalanan anda sesuai dengan permintaan dan kebutuhan. Tidak hanya sekedar menemani, para “Buddies” juga akan berbagi kisah dan pengetahuan lokal inspiratif yang akan membuat petualangan Anda semakin berkesan.
                        </p>
                    </div>
                </div>
                <div class="col-md-6 order-1 order-md-2">
                    <div class="my-hero__image">
                        <img src="{{ asset('img/about-us/main-photo.jpg') }}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="container about-us">
        <div class="row post">
            <div class="col-lg-10 mx-auto">
                <div class="story">
                    <div class="story__images">
                        <div class="story__image">
                            <img src="{{ asset('img/about-us/kisah-kami-2.jpg') }}" alt="">
                        </div>
                        <div class="story__image">
                            <img src="{{ asset('img/about-us/kisah-kami-1.jpg') }}" alt="">
                        </div>
                    </div>
                    <div class="story__body">
                        <h2 class="story__title">Kisah Kami</h2>
                        <p class="story__paragraph">
                           Kisah Travel Buddy berawal dari pelajaran-pelajaran yang diambil dari pengalaman Rizky Lasabuda selama 6 tahun tinggal di Belanda. Di saat traveling menjadi sebuah gaya hidup, kendala bahasa, keterbatasan pengetahuan, dan culture shock menjadi tantangan tersendiri dalam mewujudkan perjalanan yang mengesankan.
                        </p>
                        <p class="story__paragraph">
                            Sebagai contoh, ketika saya pertama kali ke Paris bersama orang tua, kami tidak begitu familiar dengan kota tersebut dan akhirnya hanya menikmati Menara Eiffle dan Champs Elysees saja. Atau ketika pertama kali ke Amsterdam, kami tidak terlalu mengerti mengenai transportasi umum maupun tempat-tempat wisata dan akhirnya mengandalkan bus hop-on-hop-off dan daftar “must-see” yang kami dapat dari Internet dan brosur hotel.
                        </p>
                         <p class="story__paragraph">
                             Awalnya saya merasa tidak ada yang salah dengan hal diatas, bahkan kami cukup puas dengan perjalanan tersebut. Namun ketika sudah cukup lama tinggal di luar negeri dan mengerti seluk-beluk mengenai tempat wisata, saya tersadar bahwa dengan rentang waktu dan biaya yang sama, saya bisa mendapatkan pengalaman jalan-jalan yang jauh lebih berkesan, baik dari segi tempat tujuan maupun kegiatan/aktifitas.
                        </p>
                        <p class="story__paragraph">
                            Dari sini saya melihat peluang bagi para pelajar dan WNI yang tinggal di luar negeri untuk menjadi solusi dari permasalahan tersebut. Dengan mengangkat konsep familiarity, terciptalah sebuah gagasan penyediaan jasa guide yang kenal betul dengan sejarah dan kebudayaan asing tapi masih memiliki akar budaya Indonesia. Dimulai di tahun 2017, Travel Buddy menjadi wujud nyata dari gagasan tersebut.
                        </p>
                    </div>
                </div>
                <hr>
                <div class="story">
                    <div class="story__images">
                        <div class="story__image">
                            <img src="{{ asset('img/about-us/green.jpg') }}" alt="">
                        </div>
                        <div class="story__image">
                            <img src="{{ asset('img/about-us/kisah-kami-4.jpg') }}" alt="">
                        </div>
                    </div>
                    <div class="story__body">
                        <h2 class="story__title">Dampak Sosial</h2>
                        <p class="story__paragraph">
                            Travel Buddy hadir untuk membuka prespektif baru tentang nilai-nilai kebudayaan dan keberagaman. Hal ini dapat dicapai dengan memperkenalkan kepada Traveler nilai kehidupan yang dipegang oleh budaya asing, seperti kebiasaan saling bertegur sapa, mengantri, dan budaya membaca.
                        </p>
                        <p class="story__paragraph">
                            Travel Buddy juga mengajak Traveler dari Indonesia untuk melihat gaya hidup green living di negara-negara maju dengan harapan agar para traveler lebih bisa menghargai alam dan lingkungan di negaranya sendiri. Inilah salah satu bentuk kontribusi kami dalam menjadikan pariwisata sebagai sarana untuk membawa perubahan positif untuk masyrakat Indonesia.
                        </p>
                    </div>
                </div>
                <hr>
                <div class="story">
                    <div class="story__images">
                        <div class="story__image">
                            <img src="{{ asset('img/about-us/rame-rame-2.jpg') }}" alt="">
                        </div>
                    </div>
                    <div class="story__body">
                        <h2 class="story__title">Komunitas Kami</h2>
                        <p class="story__paragraph">
                            Travel Buddy selalu berusaha untuk terus mengembangkan sebuah komunitas orang-orang yang punya semangat dan kecintaan dalam membangun Indonesia melalui parawisata. Saat ini kami sudah terhubung dengan puluhan "Buddies" yang tersebar di kota-kota besar Benua Eropa, Amerika, dan Asia.
                        </p>
                        <a href="{{ route('dashboard.buddy') }}" class="my-button my-button--orange">Bergabung dengan Kami</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/frontend/search-buddy.blade.php
@extends('frontend.layouts.main')

@section('content')
	@include('frontend.components.nav')
	<section id="search-buddy">
		<div class="container">
			<form class="form-search-city">
				<div class="form-group">
					<div class="wrapper-input">
						<input type="text" class="form-control" id="city" aria-describedby="cityHelp" placeholder='Try "Amsterdam"'>
						<button type="button" class="btn btn-search-buddy">Cari Buddy</button>
					</div>
				</div>
			</form>
			<p class="search-query">Hasil pencarian buddy dengan keyword "<span>semuanya</span>"</p>

			<div class="container card-container">
				<div class="row">
					<div class="col-3">
						<div class="card">
							<div class="pp-wrapper">
								<img class="card-img-top" src="{{asset('img/buddy-img/Griyana2.jpg')}}" alt="Card image cap">
								<div class="price-buddy">
									<p class="rate">
										IDR 120 K
										<span class="dur">/jam</span>
									</p>
								</div>
							</div>
							<div class="card-body">
								<div class="div-flex name-age">
									<h5 class="card-title">Mentari</h5>
									<p>Age: <span>25</span></p>
								</div>
								<p class="text-capitalize country"><span>den haag</span> / belanda</p>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">indonesia</p>
								</div>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">photography</p>
								</div>
								<button type="button" class="btn btn-search-buddy hollow">See Details</button>
								<button type="button" class="btn btn-search-buddy">Book Me</button>
							</div>
						</div>
					</div>
					<div class="col-3">
						<div class="card">
							<div class="pp-wrapper">
								<img class="card-img-top" src="{{asset('img/buddy-img/Griyana2.jpg')}}" alt="Card image cap">
								<div class="price-buddy">
									<p class="rate">
										IDR 120 K
										<span class="dur">/jam</span>
									</p>
								</div>
							</div>
							<div class="card-body">
								<div class="div-flex name-age">
									<h5 class="card-title">Mentari</h5>
									<p>Age: <span>25</span></p>
								</div>
								<p class="text-capitalize country"><span>den haag</span> / belanda</p>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">indonesia</p>
								</div>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">photography</p>
								</div>
								<button type="button" class="btn btn-search-buddy hollow">See Details</button>
								<button type="button" class="btn btn-search-buddy">Book Me</button>
							</div>
						</div>
					</div>
					<div class="col-3">
						<div class="card">
							<div class="pp-wrapper">
								<img class="card-img-top" src="{{asset('img/buddy-img/Griyana2.jpg')}}" alt="Card image cap">
								<div class="price-buddy">
									<p class="rate">
										IDR 120 K
										<span class="dur">/jam</span>
									</p>
								</div>
							</div>
							<div class="card-body">
								<div class="div-flex name-age">
									<h5 class="card-title">Mentari</h5>
									<p>Age: <span>25</span></p>
								</div>
								<p class="text-capitalize country"><span>den haag</span> / belanda</p>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">indonesia</p>
								</div>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">photography</p>
								</div>
								<button type="button" class="btn btn-search-buddy hollow">See Details</button>
								<button type="button" class="btn btn-search-buddy">Book Me</button>
							</div>
						</div>
					</div>
					<div class="col-3">
						<div class="card">
							<div class="pp-wrapper">
								<img class="card-img-top" src="{{asset('img/buddy-img/Griyana2.jpg')}}" alt="Card image cap">
								<div class="price-buddy">
									<p class="rate">
										IDR 120 K
										<span class="dur">/jam</span>
									</p>
								</div>
							</div>
							<div class="card-body">
								<div class="div-flex name-age">
									<h5 class="card-title">Mentari</h5>
									<p>Age: <span>25</span></p>
								</div>
								<p class="text-capitalize country"><span>den haag</span> / belanda</p>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">indonesia</p>
								</div>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">photography</p>
								</div>
								<button type="button" class="btn btn-search-buddy hollow">See Details</button>
								<button type="button" class="btn btn-search-buddy">Book Me</button>
							</div>
						</div>
					</div>
					<div class="col-3">
						<div class="card">
							<div class="pp-wrapper">
								<img class="card-img-top" src="{{asset('img/buddy-img/Griyana2.jpg')}}" alt="Card image cap">
								<div class="price-buddy">
									<p class="rate">
										IDR 120 K
										<span class="dur">/jam</span>
									</p>
								</div>
							</div>
							<div class="card-body">
								<div class="div-flex name-age">
									<h5 class="card-title">Mentari</h5>
									<p>Age: <span>25</span></p>
								</div>
								<p class="text-capitalize country"><span>den haag</span> / belanda</p>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">indonesia</p>
								</div>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">photography</p>
								</div>
								<button type="button" class="btn btn-search-buddy hollow">See Details</button>
								<button type="button" class="btn btn-search-buddy">Book Me</button>
							</div>
						</div>
					</div>
					<div class="col-3">
						<div class="card">
							<div class="pp-wrapper">
								<img class="card-img-top" src="{{asset('img/buddy-img/Griyana2.jpg')}}" alt="Card image cap">
								<div class="price-buddy">
									<p class="rate">
										IDR 120 K
										<span class="dur">/jam</span>
									</p>
								</div>
							</div>
							<div class="card-body">
								<div class="div-flex name-age">
									<h5 class="card-title">Mentari</h5>
									<p>Age: <span>25</span></p>
								</div>
								<p class="text-capitalize country"><span>den haag</span> / belanda</p>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">indonesia</p>
								</div>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">photography</p>
								</div>
								<button type="button" class="btn btn-search-buddy hollow">See Details</button>
								<button type="button" class="btn btn-search-buddy">Book Me</button>
							</div>
						</div>
					</div>
					<div class="col-3">
						<div class="card">
							<div class="pp-wrapper">
								<img class="card-img-top" src="{{asset('img/buddy-img/Griyana2.jpg')}}" alt="Card image cap">
								<div class="price-buddy">
									<p class="rate">
										IDR 120 K
										<span class="dur">/jam</span>
									</p>
								</div>
							</div>
							<div class="card-body">
								<div class="div-flex name-age">
									<h5 class="card-title">Mentari</h5>
									<p>Age: <span>25</span></p>
								</div>
								<p class="text-capitalize country"><span>den haag</span> / belanda</p>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">indonesia</p>
								</div>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">photography</p>
								</div>
								<button type="button" class="btn btn-search-buddy hollow">See Details</button>
								<button type="button" class="btn btn-search-buddy">Book Me</button>
							</div>
						</div>
					</div>
					<div class="col-3">
						<div class="card">
							<div class="pp-wrapper">
								<img class="card-img-top" src="{{asset('img/buddy-img/Griyana2.jpg')}}" alt="Card image cap">
								<div class="price-buddy">
									<p class="rate">
										IDR 120 K
										<span class="dur">/jam</span>
									</p>
								</div>
							</div>
							<div class="card-body">
								<div class="div-flex name-age">
									<h5 class="card-title">Mentari</h5>
									<p>Age: <span>25</span></p>
								</div>
								<p class="text-capitalize country"><span>den haag</span> / belanda</p>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">indonesia</p>
								</div>
								<div class="div-flex abilities">
									<img src="{{asset('img/icon/find-black.svg')}}">
									<p class="text-capitalize">photography</p>
								</div>
								<button type="button" class="btn btn-search-buddy hollow">See Details</button>
								<button type="button" class="btn btn-search-buddy">Book Me</button>
							</div>
						</div>
					</div>
				</div>
			</div>
	</section>
@endsection