routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/syarat-dan-ketentuan', function() {
    return view('frontend.help.syarat-dan-ketentuan');
});

/*
|--------------------------------------------------------------------------
| Buddy Routes
|--------------------------------------------------------------------------
*/
Route::prefix('buddy')->name('buddy.')->group(function() {
    Route::get('/','BuddyController@index')->name('home');
    
    // Route for booking a buddy
    Route::get('/{id}/book', 'BuddyController@book')->name('book');
    Route::post('/{id}/book', 'BuddyController@book')->name('book');
    Route::get('/book/success', function() {
        return view('frontend/buddy/order-success');
    })->name('book.success');
    
    // Buddy's profile
    Route::get('/{id}', 'BuddyController@profile')
        ->where(['id' => '[0-9]+'])
        ->name('profile');

    Route::post('/create', 'BuddyController@create')->name('create');
    
    Route::get('/search','BuddyController@search')->name('search');

    Route::post('order/accept','BuddyController@acceptOrder')->name('order.accept');
    Route::post('order/decline','BuddyController@declineOrder')->name('order.decline');
});

Route::get('/become-a-buddy', 'BuddyController@join')->name('buddy.join');

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::prefix('admin')
    ->name('admin.')
    ->namespace('Admin')
    ->group(function() {
    
    route::get('buddy', 'BuddyController@index')->name('buddy');
    route::get('verification', 'BuddyController@verification')->name('verification');
    //  route::get('buddy/verification', function () {
    //     return 'hello';
    // });
    // route::get('buddy/verification', 'BuddyController@verification')->name('verification')
      

    route::delete('buddy/{id}', 'BuddyController@delete')->name('buddy.delete');

    route::get('buddy/view/{id}', 'BuddyController@view')->name('buddy.view');
    
    Route::get('order', 'OrderController@index')->name('order');
    Route::put('order/status', 'OrderController@orderStatus')->name('order.status');

    Route::get('order/{id}', 'OrderController@view')->name('order.item');
    Route::post('order/confirm', 'OrderController@confirm')->name('order.confirm');
    
    Route::get('order/{id}/update', 'OrderController@updateView')->name('order.update.view');
    Route::put('order/{id}/update', 'OrderController@update')->name('order.update');
    
    Route::get('/', 'HomeController@index')->name('home');
});

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/
Route::prefix('user')
    ->name('user.')
    ->group(function() {
    
    Route::put('/password', 'UserController@changePassword')->name('changePassword');
    Route::post('/update', 'UserController@update')->name('update');
    Route::post('/update/picture', 'UserController@updatePicture')->name('updatePicture');
});


Route::prefix('bantuan')->name('help.')->group(function () {
    Route::get('/', function() {
        return view('frontend.help.menggunakan-jasa-kami');
    })->name('home');
    Route::get('menggunakan-jasa-kami', function() {
        return view('frontend.help.menggunakan-jasa-kami');
    })->name('menggunakan-jasa-kami');
    Route::get('faq', function() {
        return view('frontend.help.faq');
    })->name('faq');
});

/*
|--------------------------------------------------------------------------
| About Us
|--------------------------------------------------------------------------
*/
Route::get('/about-us', function() {
    return view('frontend.about-us');
});

/*
|--------------------------------------------------------------------------
| Dashboard
|--------------------------------------------------------------------------
*/
Route::prefix('dashboard')->name('dashboard.')->group(function() {
    Route::get('/','DashboardController@index')->name('home');
    Route::get('buddy', 'DashboardController@buddy')->name('buddy');
    Route::get('order', 'DashboardController@order')->name('order');
    Route::get('settings', 'DashboardController@settings')->name('settings');
});

/*
|--------------------------------------------------------------------------
| Email verification
|--------------------------------------------------------------------------
*/
Route::get('/register/verification', function() {
    return view('email-verif.verification');
});
Route::get('/verification', function() {
    return view('email-verif.must-verif');
});

Route::get('/register/verification/resend', 'RegisterController@resend');
Route::post('/register/verification/resend', 'RegisterController@resend');
Route::get('/verifyemail/{token}', 'RegisterController@verify');


/*
|--------------------------------------------------------------------------
| API
|--------------------------------------------------------------------------
*/
Route::get('/api/country', 'CountryController@index');
Route::get('/api/city', 'CountryController@city');
Route::get('/api/price', 'CountryController@price');

/*
|--------------------------------------------------------------------------
| For testing purposes
|--------------------------------------------------------------------------
*/
// Route::post('testpost', function(\Illuminate\Http\Request $request) {
//     echo '<pre>';
//     var_dump($request->all());
//     echo '</pre>';
// });

// Route::get('testviewmail', function() {
//     $user = \App\Models\User::find(1);

//     return view ('mail.email-verification', compact('user'));
// });

// Route::get('testmail', function() {
//     $order = \App\Order::first();
//     Mail::to('husnimun@gmail.com')
//     ->send(new \App\Mail\ResetPassword('asdwasdwasdw'));
// });

// Route::get('testmail', function() {
//     $user = \App\Models\User::find(3);
//     Mail::to('husnimunaya@gmail.com')
//         ->send(new \App\Mail\EmailVerification($user));
// });

// Route::get('mailable', function() {
//     $order = \App\Order::find(1);

//     return new App\Mail\OrderReceivedBuddy($order);
// });

// Route::get('test', function() {
//     return view('test');
// });

// Route::get('buddysearch', function(\Illuminate\Http\Request $request) {
//     $location = $request->input('location');        
//     $buddies = \App\Buddy::search($location)->get();

//     return response()->json(['data' => $buddies], 200, [], JSON_NUMERIC_CHECK);
// });

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;

class DashboardController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
    }
    
    /**
     * Shows dashboard home.
     */
    public function index(Request $request)
    {
        if (Auth::user()->verified === 0) {
            return view('email-verif.must-verif');
        }

        $user = Auth::user();
        if (!$user->isDataComplete()) {
            $request->session()->flash('info', [
                'title' => 'Halo ' . $user->name,
                'message' => "Selamat datang di Travel Buddy. Anda telah tergabung dalam komunitas traveler Indonesia dan 'Buddies' yang berada di berbagai penjuru dunia. Anda dapat menggunakan Travel Buddy untuk mencari orang Indonesia yang akan menemani selama berjalan-jalan di luar negeri. Silahkan isi form berikut untuk memulai petualangan Anda."
            ]);
        }

        return view('dashboard.index', compact('user'));
    }

    public function buddy(Request $request)
    {
        if (Auth::user()->verified === 0) {
            return view('email-verif.must-verif');
        }

        $user = Auth::user();
        if (!$user->isDataComplete()) {
            $request->session()->flash('flash-warning', [
                'message' => 'Untuk menjadi buddy, kamu harus melengkapi data personal terlebih dahulu'
            ]);
            return redirect(route('dashboard.home'));
        }
        return view('dashboard.buddy', compact('user'));
    }


    /**
     * Shows list of order.
     */
    public function order(Request $request)
    {
        if (Auth::user()->verified === 0) {
            return view('email-verif.must-verif');
        }

        $user = Auth::user();

        if (!$user->buddy) {
            return abort(403, 'Unauthorized Action');
        }
        
        return view('dashboard.order', compact('user'));
    }


    /**
     * Shows settings page.
     */
    public function settings()
    {
        if (Auth::user()->verified === 0) {
            return view('email-verif.must-verif');
        }

        $user = Auth::user();
        return view('dashboard.settings', compact('user'));
    }
}

resources/views/dashboard/index.blade.php
@extends('frontend.layouts.main')

@section('content')
@include('dashboard.components.tab')

<div class="content">
    <div class="container">
        @php
            if (Session::has('info')) {
                $profileFlashClass = 'info';
                $content = Session::get('info');
            }
            if (Session::has('warning')) {
                $profileFlashClass = 'warning';
                $content = Session::get('warning');
            }
            if (Session::has('danger')) {
                $profileFlashClass = 'danger';
                $content = Session::get('danger');
            }
        @endphp
        @if (Session::has('info') || Session::has('warning') || Session::has('danger'))
            <div class="profile__flash-message {{ $profileFlashClass }}">
                <div class="row">
                    <div class="col-md-12">
                        <a href="#" class="profile__flash-message__close">
                            <i class="fa fa-times"></i>
                        </a>
                        @if (!empty($content['title']))
                            <h4 class="profile__flash-message__title">
                                {{ $content['title'] }}
                            </h4>
                        @endif
                        <p class="profile__flash-message__body">
                            {{ $content['message']  }}
                        </p>
                    </div>
                </div>
            </div>
        @endif
        <form
            method="POST"
            action="{{ route('user.update') }}"
            enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="row">
                <div class="col-md-3">
                    <h2 class="profile__title">Foto Profil Anda</h2>
                    <div class="profile__picture-wrapper">
                        <div class="profile__picture">
                            <img id="profilePictureEl" src="{{ Helper::getProfilePicture($user) }}">
                            <div class="profile__picture-action-wrapper">
                                <a href="#" class="profile__picture-action profile__picture-action--cancel"></a>
                            </div>
                        </div>
                    </div>
                    <div>
                        <span class="photo-input__error hide"></span>
                        <label
                            for="photoInput"
                            class="my-button my-button--grey my-button--block my-button--icon-photo">
                            Ganti Foto Profil
                        </label>
                        <input
                            id="photoInput"
                            name="photo"
                            class="photo-input"
                            type="file">
                    </div>
                </div>
                <div class="col-md-6 ml-3">
                    <div>
                        <fieldset>
                            <legend class="profile__title">Informasi personal Anda</legend>
                            <div class="my-form-group {{ $errors->has('name') ? 'my-form--danger' : ''}}">
                                <label for="name">Nama Lengkap</label>
                                <input
                                    id="name"
                                    name="name"
                                    type="text"
                                    class="my-form-control"
                                    value="{{ $user->name }}"
                                    placeholder="Nama Lengkap"
                                    required autofocus>
                            </div>
                        
                            <div class="my-form-group {{ $errors->has('name') ? 'my-form--danger' : ''}}">
                                <label for="name">Email</label>
                                <input
                                    disabled
                                    id="email"
                                    name="email"
                                    type="email"
                                    class="my-form-control"
                                    value="{{ $user->email }}"
                                    placeholder="Alamat Email"
                                    required>
    
                                @if ($errors->has('email'))
                                    <span class="my-form__error">
                                        {{ $errors->first('email') }}
                                    </span>
                                @endif
                            </div>
                        
                            <div class="my-form-group {{ $errors->has('name') ? 'my-form--danger' : ''}}">
                                <label for="name">Nomor Telepon</label>
                                <input
                                    id="phone"
                                    name="phone"
                                    type="text"
                                    class="my-form-control"
                                    value="{{ $user->phone }}"
                                    placeholder="e.g. 081223227xxx"
                                    required>
                                
                                @if ($errors->has('phone'))
                                    <div class="my-form__error">
                                        {{ $errors->first('phone') }}
                                    </div>
                                @endif
                            </div>
                            <button type="submit" class="my-button my-button--orange my-button--large">Simpan</button>
                        </fieldset>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@section('script')
<script>
    {

        let photoInput = document.getElementById('photoInput');
        let profilePictureEl = document.getElementById('profilePictureEl');
        let originalSrc = profilePictureEl.src;
        let cancelBtn = document.querySelector('.profile__picture-action--cancel');
        let formError = document.querySelector('.photo-input__error');
        
        photoInput.addEventListener('change', handlePhotoInput);
        function handlePhotoInput() {
            let reader = new FileReader();
            let photoFile = photoInput.files[0];        
            const MAX_SIZE = 2000000;

            hideError();

            if (photoFile.size > MAX_SIZE) {
                showError('Ukuran gambar tidak boleh lebih dari 2MB.');
                photoInput.value = '';
                return;
            }

            if (photoFile.type !== 'image/jpeg' && photoFile.type !== 'image/png') {
                showError('Gambar harus memiliki ekstensi .png atau .jpg');
                photoInput.value = '';
                return;
            }

            reader.readAsDataURL(photoFile);
            reader.addEventListener('load', function() {
                profilePictureEl.src = reader.result;
                document.querySelector('.profile__picture').classList.add('changed');
            });
        }

        cancelBtn.addEventListener('click', function(e) {
            e.preventDefault();
            
            photoInput.value = '';
            profilePictureEl.src = originalSrc;
            
            document.querySelector('.profile__picture').classList.remove('changed');
        })

        function showError(content) {
            formError.classList.remove('hide');
            formError.innerHTML = content;
        }

        function hideError() {
            formError.classList.add('hide');
        }
    }
</script>
@endsection

resources/views/dashboard/order.blade.php
@extends('frontend.layouts.main')

@section('content')
@include('dashboard.components.tab')
<div class="content">   
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="order-received-buddy">
                    @if ($user->buddy->orders->count() > 0)
                        <div class="accordion-order__head">
                            <p>Nomor Order</p>
                            <p>Kota Pilihan</p>
                            <p>Waktu Perjalanan</p>
                            <p>Total Biaya</p>
                            <p>Status Order</p>
                        </div>
                        @foreach ($user->buddy->orders as $order)
                            <div class="tb-accordion accordion-order">
                                <div class="tb-accordion__header">
                                    <h3 class="tb-accordion__title tb-accordion__toggler">
                                        Order #{{ $order->order_number }}
                                    </h3>
                                    <p class="accordion-order__destination">
                                        {{ $order->trip_details['destination'] }}
                                    </p>
                                    <p class="accordion-order__date">
                                        {{ (new Carbon($order->start_date))->format('d/m/Y') }} - {{ (new Carbon($order->end_date))->format('d/m/Y') }}
                                    </p>
                                    <p class="accordion-order__price">
                                        {{ Helper::formatCurrency($order->price_estimation) }}
                                    </p>
                                    <div class="accordion-order__action">
                                        @if ($order->status === \App\Order::ORDER_SUBMITTED)
                                             <tb-modal
                                                class-name="my-button my-button--peach"
                                                button-value="Accept">
                                                <template slot="body">
                                                    <p>Apakah Anda yakin akan menerima order?</p>
                                                </template>
                                                <template slot="proceed">
                                                    <button
                                                        type="submit"
                                                        form="order{{ $order->id }}Accept"
                                                        class="my-button my-button--peach">
                                                        Accept
                                                    </button>
                                                </template>
                                            </tb-modal>
                                            <tb-modal
                                                class-name="my-button my-button--grey"
                                                button-value="Decline">
                                                <template slot="body">
                                                    <p>Apakah Anda yakin akan menolak order?</p>
                                                </template>
                                                <template slot="proceed">
                                                    <button
                                                        type="submit"
                                                        form="order{{ $order->id }}Decline"
                                                        class="my-button my-button--peach">Decline
                                                    </button>
                                                </template>
                                            </tb-modal>
                                            <form
                                                method="POST"
                                                id="order{{ $order->id }}Accept"
                                                style="display: none"
                                                action="{{ route('buddy.order.accept') }}">
                                                {{ csrf_field() }}
                                                <input type="hidden" name="order_id" value="{{ $order->id }}">
                                            </form>
                                            <form
                                                method="POST"
                                                id="order{{ $order->id }}Decline"
                                                style="display: none"
                                                action="{{ route('buddy.order.decline') }}">
                                                {{ csrf_field() }}
                                                <input type="hidden" name="order_id" value="{{ $order->id }}">
                                            </form>
                                        @elseif ($order->status === \App\Order::ORDER_ACCEPTED)
                                            Order diterima
                                        @elseif ($order->status === \App\Order::ORDER_DECLINED)
                                            Order ditolak
                                        @endif
                                    </div>
                                </div>
                                <div class="tb-accordion__content">
                                    <div class="tb-accordion__body">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="accordion-order__row">
                                                    <div class="accordion-order__cell title">Pelanggan</div>
                                                    <div class="accordion-order__cell value">{{ $order->name }}</div>
                                                </div>
                                                <div class="accordion-order__row">
                                                    <div class="accordion-order__cell title">Email</div>
                                                    <div class="accordion-order__cell value">{{ $order->email }}</div>
                                                </div>
                                                @if($order->payment_status = "PAYMENT_UNPAID")
                                                <div class="accordion-order__row">
                                                   <div class="accordion-order__cell title"><!--  Telepon -->belom bayar</div>
                                                    <div class="accordion-order__cell value"><!--{{ $order->phone }}--></div>
                                                </div>
                                                @else
                                                <div class="accordion-order__row">
                                                   <div class="accordion-order__cell title"><!--  Telepon -->bayar</div>
                                                    <div class="accordion-order__cell value"><!--{{ $order->phone }}--></div>
                                                </div>
                                                @endif

                                                <div class="accordion-order__row">
                                                    <div class="accordion-order__cell title">Rombongan</div>
                                                    <div class="accordion-order__cell value">{{ $order->trip_details['total_adults'] }} {{ ' orang dewasa' }}@if ((int) $order->trip_details['total_children'] > 0), {{ $order->trip_details['total_children'] }} orang anak @endif
                                                    </div>
                                                </div>
                                                <div class="accordion-order__row">
                                                    <div class="accordion-order__cell title">Tujuan Perjalanan</div>
                                                    <div class="accordion-order__cell value">
                                                        @foreach ($order->trip_details['trip_type'] as $index => $type)
                                                            {{ $type }}
                                                            @if ($index !== count($order->trip_details['trip_type']) - 1)
                                                                ,
                                                            @endif
                                                        @endforeach
                                                    </div>
                                                </div>
                                                <div class="accordion-order__row">
                                                    <div class="accordion-order__cell title">Deskripsi Perjalanan</div>
                                                    <div class="accordion-order__cell value"></div>
                                                </div>
                                                <div class="accordion-order__row">
                                                    <div class="accordion-order__cell value full">{{ $order->trip_details['trip_description'] }}</div>
                                                </div>
                                                <div class="accordion-order__row">
                                                    <div class="accordion-order__cell title">Pesan untuk Buddy</div>
                                                    <div class="accordion-order__cell value"></div>
                                                </div>
                                                <div class="accordion-order__row">
                                                    <div class="accordion-order__cell value full">
                                                        {{ $order->message_to_buddy }}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="accordion-order__row">
                                                    <div class="accordion-order__cell title">Detail Perjalanan:</div>
                                                </div>
                                                <div class="accordion-order__row">
                                                    <br>
                                                </div>
                                                @php
                                                    $startDate = new Carbon($order->start_date);
                                                    $endDate = (new Carbon($order->end_date))->addDay();

                                                    $interval = new DateInterval('P1D');
                                                    $dateRange = new DatePeriod($startDate, $interval ,$endDate);
                                                @endphp
                                                <div class="accordion-order__row">
                                                    <div class="accordion-order__cell">Tanggal</div>
                                                    <div class="accordion-order__cell">Waktu</div>
                                                    <div class="accordion-order__cell">Harga</div>
                                                </div>
                                                @foreach ($dateRange as $index => $date)
                                                    @php
                                                        $dt = new Carbon($date);
                                                        $formatedDate = $dt->formatLocalized('%e %B %Y');
                                                    @endphp
                                                        <div class="accordion-order__row">
                                                            <div class="accordion-order__cell value">{{ $formatedDate }}</div>
                                                            <div class="accordion-order__cell value">{{ $order->hours_per_day[$index] }} Jam</div>
                                                            <div class="accordion-order__cell value">{{ Helper::formatCurrency((int) $order->price_per_day * (int) $order->hours_per_day[$index]) }}</div>
                                                        </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    @else
                        <h2 class="heading-3" style="min-height:320px">
                            Anda belum memiliki order
                        </h2>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection