routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/syarat-dan-ketentuan', function() {
    return view('frontend.help.syarat-dan-ketentuan');
});

/*
|--------------------------------------------------------------------------
| Buddy Routes
|--------------------------------------------------------------------------
*/
Route::prefix('buddy')->name('buddy.')->group(function() {
    Route::get('/','BuddyController@index')->name('home');
    
    // Route for booking a buddy
    Route::get('/{id}/book', 'BuddyController@book')->name('book');
    Route::post('/{id}/book', 'BuddyController@book')->name('book');
    Route::get('/book/success', function() {
        return view('frontend/buddy/order-success');
    })->name('book.success');
    
    // Buddy's profile
    Route::get('/{id}', 'BuddyController@profile')
        ->where(['id' => '[0-9]+'])
        ->name('profile');

    Route::post('/create', 'BuddyController@create')->name('create');
    
    Route::get('/search','BuddyController@search')->name('search');

    Route::post('order/accept','BuddyController@acceptOrder')->name('order.accept');
    Route::post('order/decline','BuddyController@declineOrder')->name('order.decline');
});

Route::get('/become-a-buddy', 'BuddyController@join')->name('buddy.join');

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::prefix('admin')
    ->name('admin.')
    ->namespace('Admin')
    ->group(function() {
    
    route::get('buddy', 'BuddyController@index')->name('buddy');
    route::get('verification', 'BuddyController@verification')->name('verification');
    //  route::get('buddy/verification', function () {
    //     return 'hello';
    // });
    // route::get('buddy/verification', 'BuddyController@verification')->name('verification')
      

    route::delete('buddy/{id}', 'BuddyController@delete')->name('buddy.delete');

    route::get('buddy/view/{id}', 'BuddyController@view')->name('buddy.view');
    
    Route::get('order', 'OrderController@index')->name('order');
    Route::put('order/status', 'OrderController@orderStatus')->name('order.status');

    Route::get('order/{id}', 'OrderController@view')->name('order.item');
    Route::post('order/confirm', 'OrderController@confirm')->name('order.confirm');
    
    Route::get('order/{id}/update', 'OrderController@updateView')->name('order.update.view');
    Route::put('order/{id}/update', 'OrderController@update')->name('order.update');
    
    Route::get('/', 'HomeController@index')->name('home');
});

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/
Route::prefix('user')
    ->name('user.')
    ->group(function() {
    
    Route::put('/password', 'UserController@changePassword')->name('changePassword');
    Route::post('/update', 'UserController@update')->name('update');
    Route::post('/update/picture', 'UserController@updatePicture')->name('updatePicture');
});


Route::prefix('bantuan')->name('help.')->group(function () {
    Route::get('/', function() {
        return view('frontend.help.menggunakan-jasa-kami');
    })->name('home');
    Route::get('menggunakan-jasa-kami', function() {
        return view('frontend.help.menggunakan-jasa-kami');
    })->name('menggunakan-jasa-kami');
    Route::get('faq', function() {
        return view('frontend.help.faq');
    })->name('faq');
});

/*
|--------------------------------------------------------------------------
| About Us
|--------------------------------------------------------------------------
*/
Route::get('/about-us', function() {
    return view('frontend.about-us');
});

/*
|--------------------------------------------------------------------------
| Dashboard
|--------------------------------------------------------------------------
*/
Route::prefix('dashboard')->name('dashboard.')->group(function() {
    Route::get('/','DashboardController@index')->name('home');
    Route::get('buddy', 'DashboardController@buddy')->name('buddy');
    Route::get('order', 'DashboardController@order')->name('order');
    Route::get('settings', 'DashboardController@settings')->name('settings');
});

/*
|--------------------------------------------------------------------------
| Email verification
|--------------------------------------------------------------------------
*/
Route::get('/register/verification', function() {
    return view('email-verif.verification');
});
Route::get('/verification', function() {
    return view('email-verif.must-verif');
});

Route::get('/register/verification/resend', 'RegisterController@resend');
Route::post('/register/verification/resend', 'RegisterController@resend');
Route::get('/verifyemail/{token}', 'RegisterController@verify');


/*
|--------------------------------------------------------------------------
| API
|--------------------------------------------------------------------------
*/
Route::get('/api/country', 'CountryController@index');
Route::get('/api/city', 'CountryController@city');
Route::get('/api/price', 'CountryController@price');

/*
|--------------------------------------------------------------------------
| For testing purposes
|--------------------------------------------------------------------------
*/
// Route::post('testpost', function(\Illuminate\Http\Request $request) {
//     echo '<pre>';
//     var_dump($request->all());
//     echo '</pre>';
// });

// Route::get('testviewmail', function() {
//     $user = \App\Models\User::find(1);

//     return view ('mail.email-verification', compact('user'));
// });

// Route::get('testmail', function() {
//     $order = \App\Order::first();
//     Mail::to('husnimun@gmail.com')
//     ->send(new \App\Mail\ResetPassword('asdwasdwasdw'));
// });

// Route::get('testmail', function() {
//     $user = \App\Models\User::find(3);
//     Mail::to('husnimunaya@gmail.com')
//         ->send(new \App\Mail\EmailVerification($user));
// });

// Route::get('mailable', function() {
//     $order = \App\Order::find(1);

//     return new App\Mail\OrderReceivedBuddy($order);
// });

// Route::get('test', function() {
//     return view('test');
// });

// Route::get('buddysearch', function(\Illuminate\Http\Request $request) {
//     $location = $request->input('location');        
//     $buddies = \App\Buddy::search($location)->get();

//     return response()->json(['data' => $buddies], 200, [], JSON_NUMERIC_CHECK);
// });

app/Verification.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Iatstuti\Database\Support\CascadeSoftDeletes;


class verification extends Model
{
    use Searchable;
    use SoftDeletes;
    use CascadeSoftDeletes;
    
    /**
     * Get the index name for the model.
     *
     * @return string
     */
    public function searchableAs()
    {
        return 'buddies_index';
    }

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * Enable soft delete cascade
     * 
     * @var array
     */
    protected $cascadeDeletes = ['orders'];

    /**
     * The table associated with the model
    */
    protected $table = 'buddies';

    protected $casts = [
        'city_coverage' => 'array',
        'interests' => 'array',
    ];

    /**
     * User that belongs to the buddy
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    /**
     * Order that belongs to the buddy
     */
    public function orders()
    {
        return $this->hasMany('App\Order');
    }

    public function age()
    {
        return (int) date('Y') - (int) $this->birthyear;
    }

    /**
     * Check if buddy has order given the order id.
     * @param $orderId
     * 
     * @return true if buddy has that order.
     */
    public function hasOrder($orderId)
    {
        $order = $this->orders()->find($orderId);

        if ($order) {
            return true;
        } else {
            return false;
        }
    }
  
}

resources/views/admin/verification/index.blade.php
@extends('admin.layouts.main')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-5 mb-3">
                @if (Session::has('success'))
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-success">{{ Session::get('success') }}</li>
                    </ul>
                @endif
            </div>
        </div>
        <div class="row">
            @if ($buddies->count() > 0)
                <div class="card mb-3">
                    <div class="card-header">
                        <i class="fa fa-table"></i> Daftarin Buddy
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Nokop.</th>
                                        <th>Nama</th>
                                        <th>Email</th>
                                        <th>HP</th>
                                        <th>Domisili</th>
                                        <th>Kota Cakupan</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>No.</th>
                                        <th>Nama</th>
                                        <th>Email</th>
                                        <th>HP</th>
                                        <th>Domisili</th>
                                        <th>Kota Cakupan</th>
                                        <th>ktp</th>
                                        <th></th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach ($buddies as $index => $buddy)
                                        <tr>
                                            <td>{{ $index + 1 }}</td>
                                            <td>{{ $buddy->user->name }}</td>
                                            <td>{{ $buddy->user->email }}</td>
                                            <td>{{ $buddy->user->phone }}</td>
                                            <td>{{ $buddy->city }}, {{ $buddy->country }}</td>
                                            <td>{{ Helper::printArray($buddy->city_coverage) }}</td>
                                            <td>{{ Helper::getProfilePicture($user) }}</td>
                                            <td>
                                                <a href="{{ route('admin.buddy.view', ['id' => $buddy->id]) }}" class="btn btn-info">Lihat Buddy</a>
                                                <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteBuddy{{ $index }}">
                                                Hapus Buddy
                                                </button>

                                                <!-- Modal -->
                                                <div class="modal fade" id="deleteBuddy{{ $index }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                    <div class="modal-dialog" role="document">
                                                        <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <p>
                                                                Apakah Anda yakin akan menghapus Buddy {{ $buddy->user->name }}?
                                                                <br>
                                                                <br>
                                                                <span class="text-danger">Perhatian: Order yang dimiliki oleh Buddy {{ $buddy->user->name }} akan ikut terhapus.</span>
                                                            </p>

                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>

                                                            <form
                                                                style="display:none"
                                                                id="formDeleteBuddy{{ $buddy->id }}"
                                                                method="POST"
                                                                action="{{ route('admin.buddy.delete', ['id' => $buddy->id]) }}">
                                                                {{ csrf_field() }}
                                                                {{ method_field('DELETE')}}
                                                            </form>
                                                            <button type="submit" form="formDeleteBuddy{{ $buddy->id }}" class="btn btn-danger">Hapus Buddy</button>
                                                        </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            @else
                <div class="card mb-3">
                    <div class="card-header">
                        Daftar Buddy
                    </div>
                    <div class="card-body">
                        <p>Data buddy belum ada</p>
                    </div>
                </div>
            @endif
        </div>
    </div>
@endsection

resources/views/admin/verification/view.blade.php
@extends('admin.layouts.main')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row mb-3">
            <div class="col-md-6 ml-3">
                <div class="profile__section">
                    <h1 class="profile__name">{{ $buddy->nickname }}</h1>
                    <p class="profile__description">{{ $buddy->description }}</p>
                </div>
                
                <div class="profile__section">
                    <h2 class="profile__title">Kota Cakupan</h2>
                    <ul class="profile__list city-coverage">
                        @foreach ($buddy->city_coverage as $city)
                            <li>{{ $city }}, {{ $buddy->country }}</li>
                        @endforeach
                    </ul>
                </div>

                <div class="profile__section">
                    <h2 class="profile__title">Kemampuan dan Minat Travelling</h2>
                    
                    <h3 class="profile__skills language">Bahasa</h3>
                    <ul class="profile__list">
                        <li>{{ $buddy->language }}</li>
                    </ul>
                    
                    <h3 class="profile__skills interest">Personal Interest</h3>
                    <ul class="profile__list">
                        <li>{{ Helper::printArray($buddy->interests) }}</li>
                    </ul>
                    
                    <h3 class="profile__skills skill">Additional Skills</h3>
                    <ul class="profile__list">
                        <li>{{ $buddy->skills }}</li>
                    </ul>
                    
                </div>

                <div class="profile__section">
                    <h2 class="profile__title">Pengalaman sebagai Buddy Travelling</h2>
                    <p class="profile__description">{{ $buddy->experience }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection