routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/syarat-dan-ketentuan', function() {
    return view('frontend.help.syarat-dan-ketentuan');
});

/*
|--------------------------------------------------------------------------
| Buddy Routes
|--------------------------------------------------------------------------
*/
Route::prefix('buddy')->name('buddy.')->group(function() {
    Route::get('/','BuddyController@index')->name('home');
    
    // Route for booking a buddy
    Route::get('/{id}/book', 'BuddyController@book')->name('book');
    Route::post('/{id}/book', 'BuddyController@book')->name('book');
    Route::get('/book/success', function() {
        return view('frontend/buddy/order-success');
    })->name('book.success');
    
    // Buddy's profile
    Route::get('/{id}', 'BuddyController@profile')
        ->where(['id' => '[0-9]+'])
        ->name('profile');

    Route::post('/create', 'BuddyController@create')->name('create');
    
    Route::get('/search','BuddyController@search')->name('search');

    Route::post('order/accept','BuddyController@acceptOrder')->name('order.accept');
    Route::post('order/decline','BuddyController@declineOrder')->name('order.decline');
});

Route::get('/become-a-buddy', 'BuddyController@join')->name('buddy.join');

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::prefix('admin')
    ->name('admin.')
    ->namespace('Admin')
    ->group(function() {
    
    route::get('buddy', 'BuddyController@index')->name('buddy');
    route::get('verification', 'BuddyController@verification')->name('verification');
    //  route::get('buddy/verification', function () {
    //     return 'hello';
    // });
    // route::get('buddy/verification', 'BuddyController@verification')->name('verification')
      

    route::delete('buddy/{id}', 'BuddyController@delete')->name('buddy.delete');

    route::get('buddy/view/{id}', 'BuddyController@view')->name('buddy.view');
    
    Route::get('order', 'OrderController@index')->name('order');
    Route::put('order/status', 'OrderController@orderStatus')->name('order.status');

    Route::get('order/{id}', 'OrderController@view')->name('order.item');
    Route::post('order/confirm', 'OrderController@confirm')->name('order.confirm');
    
    Route::get('order/{id}/update', 'OrderController@updateView')->name('order.update.view');
    Route::put('order/{id}/update', 'OrderController@update')->name('order.update');
    
    Route::get('/', 'HomeController@index')->name('home');
});

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/
Route::prefix('user')
    ->name('user.')
    ->group(function() {
    
    Route::put('/password', 'UserController@changePassword')->name('changePassword');
    Route::post('/update', 'UserController@update')->name('update');
    Route::post('/update/picture', 'UserController@updatePicture')->name('updatePicture');
});


Route::prefix('bantuan')->name('help.')->group(function () {
    Route::get('/', function() {
        return view('frontend.help.menggunakan-jasa-kami');
    })->name('home');
    Route::get('menggunakan-jasa-kami', function() {
        return view('frontend.help.menggunakan-jasa-kami');
    })->name('menggunakan-jasa-kami');
    Route::get('faq', function() {
        return view('frontend.help.faq');
    })->name('faq');
});

/*
|--------------------------------------------------------------------------
| About Us
|--------------------------------------------------------------------------
*/
Route::get('/about-us', function() {
    return view('frontend.about-us');
});

/*
|--------------------------------------------------------------------------
| Dashboard
|--------------------------------------------------------------------------
*/
Route::prefix('dashboard')->name('dashboard.')->group(function() {
    Route::get('/','DashboardController@index')->name('home');
    Route::get('buddy', 'DashboardController@buddy')->name('buddy');
    Route::get('order', 'DashboardController@order')->name('order');
    Route::get('settings', 'DashboardController@settings')->name('settings');
});

/*
|--------------------------------------------------------------------------
| Email verification
|--------------------------------------------------------------------------
*/
Route::get('/register/verification', function() {
    return view('email-verif.verification');
});
Route::get('/verification', function() {
    return view('email-verif.must-verif');
});

Route::get('/register/verification/resend', 'RegisterController@resend');
Route::post('/register/verification/resend', 'RegisterController@resend');
Route::get('/verifyemail/{token}', 'RegisterController@verify');


/*
|--------------------------------------------------------------------------
| API
|--------------------------------------------------------------------------
*/
Route::get('/api/country', 'CountryController@index');
Route::get('/api/city', 'CountryController@city');
Route::get('/api/price', 'CountryController@price');

/*
|--------------------------------------------------------------------------
| For testing purposes
|--------------------------------------------------------------------------
*/
// Route::post('testpost', function(\Illuminate\Http\Request $request) {
//     echo '<pre>';
//     var_dump($request->all());
//     echo '</pre>';
// });

// Route::get('testviewmail', function() {
//     $user = \App\Models\User::find(1);

//     return view ('mail.email-verification', compact('user'));
// });

// Route::get('testmail', function() {
//     $order = \App\Order::first();
//     Mail::to('husnimun@gmail.com')
//     ->send(new \App\Mail\ResetPassword('asdwasdwasdw'));
// });

// Route::get('testmail', function() {
//     $user = \App\Models\User::find(3);
//     Mail::to('husnimunaya@gmail.com')
//         ->send(new \App\Mail\EmailVerification($user));
// });

// Route::get('mailable', function() {
//     $order = \App\Order::find(1);

//     return new App\Mail\OrderReceivedBuddy($order);
// });

// Route::get('test', function() {
//     return view('test');
// });

// Route::get('buddysearch', function(\Illuminate\Http\Request $request) {
//     $location = $request->input('location');        
//     $buddies = \App\Buddy::search($location)->get();

//     return response()->json(['data' => $buddies], 200, [], JSON_NUMERIC_CHECK);
// });

app/Buddy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Iatstuti\Database\Support\CascadeSoftDeletes;


class Buddy extends Model
{
    use Searchable;
    use SoftDeletes;
    use CascadeSoftDeletes;
    
    /**
     * Get the index name for the model.
     *
     * @return string
     */
    public function searchableAs()
    {
        return 'buddies_index';
    }

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * Enable soft delete cascade
     * 
     * @var array
     */
    protected $cascadeDeletes = ['orders'];

    /**
     * The table associated with the model
    */
    protected $table = 'buddies';

    protected $casts = [
        'city_coverage' => 'array',
        'interests' => 'array',
    ];

    /**
     * User that belongs to the buddy
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    /**
     * Order that belongs to the buddy
     */
    public function orders()
    {
        return $this->hasMany('App\Order');
    }

    public function age()
    {
        return (int) date('Y') - (int) $this->birthyear;
    }

    /**
     * Check if buddy has order given the order id.
     * @param $orderId
     * 
     * @return true if buddy has that order.
     */
    public function hasOrder($orderId)
    {
        $order = $this->orders()->find($orderId);

        if ($order) {
            return true;
        } else {
            return false;
        }
    }
  
}

app/Http/Controllers/Admin/BuddyController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Buddy;
use Illuminate\Support\Facades\Gate;

class BuddyController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Show all buddies.
     */
    public function index()
    {
        if (!Gate::allows('do-admin-action')) abort(403);

        $buddies = Buddy::all();
        return view('admin.buddy.index', compact('buddies'));
    }

    /**
     * View individual buddy.
     */
    public function view($id)
    {
        if (!Gate::allows('do-admin-action')) abort(403);

        $buddy = Buddy::findOrFail($id);
        return redirect(route('buddy.profile', ['id' => $id]));
    }

    /**
     * Delete buddy
     */
    public function delete($id)
    {
        if (!Gate::allows('do-admin-action')) abort(403);

        $buddy = Buddy::findOrFail($id);
        $buddy->delete();

        \Session::flash('success', 'Buddy telah dihapus.');
        return redirect(route('admin.buddy'));
    }
}

resources/views/frontend/buddy/components/buddy-card.blade.php
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,700,900" rel="stylesheet"> 
 
 <script>  
    $('#myModal1').on('shown.bs.modal', function () {
  $('#myInput').trigger('focus')
})
</script>



<div class="card">
    <div class="profile__picture-wrapper">
        <div class="pp-wrapper">
            <img class="card-img-top" src="{{ Helper::getProfilePicture($buddy->user) }}" alt="Buddy picture">
            <div class="price-buddy">
                <p class="rate">
                    {{ Helper::formatCurrency($buddy->price, 'IDR') }}
                    <span class="dur">/jam</span>
                </p>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="div-flex name-age">
            <h5 class="card-title">{{ $buddy->nickname }}</h5>
            <p>Age: <span>{{ $buddy->age() }}</span></p>
        </div>
        <p class="text-capitalize country"><span>{{ Helper::printArray($buddy->city_coverage)  }}</span> / {{ $buddy->country }}</p>
        <div class="div-flex abilities">
            <i class="fas fa-comment-alt abilities__icon"></i>
            <p class="text-capitalize">{{ $buddy->language }}</p>
        </div>
        <div class="div-flex abilities">
            <i class="fa fa-heart abilities__icon"></i>
            <p class="text-capitalize">{{ Helper::printArray($buddy->interests) }}</p>
        </div>
         @if (Auth::check())
        <div class="div-flex button-wrapper">
            <a href="{{ route('buddy.profile', ['id' => $buddy->id]) }}" class="btn btn-search-buddy hollow">See Details</a>
            <a href="{{ route('buddy.book', ['id' => $buddy->id]) }}" class="btn btn-search-buddy" >Book Me</a>
            @else
             <div class="div-flex button-wrapper">
                <a href="" class="btn btn-search-buddy hollow" data-toggle="modal" data-target="#myModal1">See Details</a>
            <a href="" class="btn btn-search-buddy" data-toggle="modal" data-target="#myModal1">Book Me</a>
          @endif
        </div>
    </div>
</div>


<div class="modal fade" id="myModal1" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
       
        <div class="modal-header">
           
           <button type="button" class="close" data-dismiss="modal">&times;</button>
       <br>
          <h4 class="modal-title"></h4></div>
        
        <div class="modal-body">
            <div class="modal-body1">
            <div class="modalimage"><img src="{{asset('img/logo.png')}}" alt="" style="width: 100%;"></div>
            
        </div>
          <h2 class="popups">WUJUDKAN IMPIANMU</h2>
          <p class="popups">Mau Tau lebih Lengkap Tentang Buddy Kita.</p>
          <p class="popups">Register Dulu Yuk.</p>
          <p style="text-align:center;"><a href="https://travelbuddy.id/register" class="my-button my-button--orange" style="border-radius: 9px!important;font-size: 1.1rem!important;font-weight: 500!important;margin-top: 20px!important;">Gabung Sekarang</a></p>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
        </div>
      </div>
      </div>
    </div>  